import { useState } from 'react'
import { useApi } from '../hooks/useApi'
const inputStyle={padding:'10px 14px',background:'var(--bg-body)',border:'1px solid var(--border)',borderRadius:'8px',fontSize:'13px',color:'var(--fg-0)',outline:'none',width:'100%'}
const btn={padding:'9px 14px',background:'var(--primary)',color:'#fff',border:'none',borderRadius:'8px',fontSize:'13px',cursor:'pointer'}
function Header(){return <div style={{marginBottom:24}}><h2 style={{fontSize:20,fontWeight:700}}>Plugins</h2><p style={{fontSize:13,color:'var(--fg-2)'}}>Installed plugins, marketplace, and AI generator</p></div>}
function Card({children}){return <div className='card' style={{marginBottom:20}}>{children}</div>}
export default function Plugins(){
 const [tab,setTab]=useState('installed'); const {data:plugins,reload}=useApi('/api/plugins'); const {data:store}=useApi('/api/plugins/store'); const [prompt,setPrompt]=useState(''); const [code,setCode]=useState('')
 async function install(p){await fetch('/api/plugins',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',...p})});reload()}
 async function gen(){const r=await fetch('/api/plugins/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'generated',prompt})}); const j=await r.json(); setCode(j.code)}
 return <div className='fade-in'><Header/><div style={{display:'flex',gap:8,marginBottom:16}}>{['installed','store','generate'].map(t=><button key={t} style={{...btn,background:tab===t?'var(--primary)':'var(--bg-card)',color:tab===t?'#fff':'var(--fg-1)',border:'1px solid var(--border)'}} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='installed'&&<Card>{plugins?.length?plugins.map(p=><div key={p.id} style={{padding:12,borderBottom:'1px solid var(--border)'}}><b>{p.name}</b><p style={{fontSize:12,color:'var(--fg-2)'}}>{p.description||'Custom plugin'}</p></div>):<div className='empty-state'><div className='icon'>🧩</div><p>No plugins installed.</p></div>}</Card>}{tab==='store'&&<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}>{(store||[]).map(p=><Card key={p.name}><h3>{p.name}</h3><p style={{fontSize:13,color:'var(--fg-2)'}}>{p.description}</p><span className='badge badge-info'>{p.category}</span><br/><button style={{...btn,marginTop:12}} onClick={()=>install(p)}>Install</button></Card>)}</div>}{tab==='generate'&&<Card><textarea style={{...inputStyle,minHeight:100}} placeholder='Describe plugin...' value={prompt} onChange={e=>setPrompt(e.target.value)}/><button style={{...btn,marginTop:12}} onClick={gen}>Generate</button><pre style={{whiteSpace:'pre-wrap',marginTop:16}}>{code}</pre></Card>}</div>
}
