import { useState } from 'react'
import { useApi } from '../hooks/useApi'

const inputStyle={padding:'10px 14px',background:'var(--bg-body)',border:'1px solid var(--border)',borderRadius:'8px',fontSize:'13px',color:'var(--fg-0)',outline:'none',width:'100%'}
const btn={padding:'9px 14px',background:'var(--primary)',color:'#fff',border:'none',borderRadius:'8px',fontSize:'13px',cursor:'pointer'}
function Header({title,sub}){return <div style={{marginBottom:24}}><h2 style={{fontSize:20,fontWeight:700}}>{title}</h2><p style={{fontSize:13,color:'var(--fg-2)'}}>{sub}</p></div>}
function Card({children}){return <div className='card' style={{marginBottom:20}}>{children}</div>}
function Empty({icon,text}){return <div className='empty-state'><div className='icon'>{icon}</div><p>{text}</p></div>}

export default function Routing(){const {data:combos,reload}=useApi('/api/combos'); const {data:models}=useApi('/v1/models'); const {data:lb}=useApi('/api/load-balancer'); const [name,setName]=useState(''); const [model,setModel]=useState(''); async function add(){await fetch('/api/combos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,models:[model],strategy:'priority'})});setName('');reload()} async function setStrategy(s){await fetch('/api/load-balancer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({strategy:s})});location.reload()} return <div className='fade-in'><Header title='Routing & Combos' sub='Create combo models, aliases, and load-balancer strategy'/><Card><h3 className='card-title'>Load Balancer</h3><div style={{display:'flex',gap:8,marginTop:12}}>{['priority','round-robin','least-connections','random'].map(s=><button key={s} onClick={()=>setStrategy(s)} style={{...btn,background:lb?.strategy===s?'var(--primary)':'var(--bg-body)',color:lb?.strategy===s?'#fff':'var(--fg-1)',border:'1px solid var(--border)'}}>{s}</button>)}</div></Card><Card><h3 className='card-title'>Create Combo</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr auto',gap:10,marginTop:12}}><input style={inputStyle} placeholder='combo name' value={name} onChange={e=>setName(e.target.value)}/><select style={inputStyle} value={model} onChange={e=>setModel(e.target.value)}>{(models?.data||[]).map(m=><option key={m.id}>{m.id}</option>)}</select><button style={btn} onClick={add}>Add</button></div></Card><Card><h3 className='card-title'>Combos</h3><pre style={{whiteSpace:'pre-wrap',fontSize:12}}>{JSON.stringify(combos,null,2)}</pre></Card></div>}
